task : DNS
---
model:
  type : TRUMEA
  type_FBlock : "FGRU"
  type_TBlock : "TGRU"
  type_CBlcok : "None"
  kernel_type : next #orig, next, GConv
  skipGRU : False
  phase_encoder : "PE"
  T_FGRU : False
  PLC : False
  PLC_alpha : 0.3
  architecture : {
    "encoder": {
        "enc1": {"in_channels": 4, "out_channels": 64, "kernel_size": [1, 5], "stride": [1,2], "padding": [0,2]},
        "enc2": {"in_channels": 64, "out_channels": 64, "kernel_size": [1, 3], "stride": [1,1], "padding": [0,1], "groups": 64},
        "enc3": {"in_channels": 64, "out_channels": 64, "kernel_size": [1, 5], "stride": [1,2], "padding": [0,2], "groups":64},
        "enc4": {"in_channels": 64, "out_channels": 64, "kernel_size": [1, 3], "stride": [1,1], "padding": [0,1], "groups": 64},
        "enc5": {"in_channels": 64, "out_channels": 64, "kernel_size": [1, 5], "stride": [1,2], "padding": [0,2], "groups": 64},
         ## orig
        #"enc6": {"in_channels": 64, "out_channels": 64, "kernel_size": [1, 3], "stride": [1,2], "padding": [0,1], "groups": 64}
         ## FSABlock
        "enc6": {"in_channels": 64, "out_channels": 64, "kernel_size": [1, 3], "stride": [1,2], "padding": [0,1], "groups": 32}
    },
    "decoder": {
        ## orig
        #"dec6": {"in_channels": 128, "out_channels": 64, "kernel_size": [1, 3], "stride": [1, 2], "padding": [0, 1]},
        ## FSABlock
        "dec6": {"in_channels": 128, "out_channels": 64, "kernel_size": [1, 3], "stride": [1, 2], "padding": [0, 1]},
        "dec5": {"in_channels": 128, "out_channels": 64, "kernel_size": [1, 5], "stride": [1, 2], "padding": [0, 2]},
        "dec4": {"in_channels": 128, "out_channels": 64, "kernel_size": [1, 3], "stride": [1, 1], "padding": [0, 1]},
        "dec3": {"in_channels": 128, "out_channels": 64, "kernel_size": [1, 5], "stride": [1, 2], "padding": [0, 2]},
        "dec2": {"in_channels": 128, "out_channels": 64, "kernel_size": [1, 3], "stride": [1, 1], "padding": [0, 1]},
        "dec1": {"in_channels": 128, "out_channels": 4, "kernel_size": [1, 5], "stride": [1, 2], "padding": [0, 2]}
    },
    "PE": {"in_channels": 1, "out_channels" : 4, "type_norm" : "BatchNorm2d","bias" : True},
    "FGRU": {"in_channels": 64, "hidden_size": 64, "out_channels": 64},
    "FSA": {"in_channels": 64, "hidden_size": 64, "out_channels": 64},
    "CSA": {"in_channels": 17, "hidden_size": 17, "out_channels": 17},
    "TGRU": {"in_channels": 64, "hidden_size": 64, "out_channels": 64, "state_size": 17},
    "MEA": {"in_channels": 4, "mag_f_dim": 3}
}

---
train:
  epoch: 20
  batch_size: 24
  num_workers: 24
  optimizer: 'Adam'
  Adam: 0.001
  adabound:
    initial: 0.001
    final: 0.05
  AdamW:
    lr: 0.001
  summary_interval: 500
  validation_interval: 100
  checkpoint_interval: 1000
---
loss:
  type: 'TRUNetLoss'
  wSDRLoss :
    alpha : 0.99
  mwMSELoss : 
    alpha : 0.9
  wSDRLoss :
    alpha : 0.99
  HybridLoss :
    alpha : 0.9

---
scheduler: # Plateau, oneCycle, CosineAnnealingLR, None
  type: 'Plateau'
  oneCycle:
    max_lr: 0.001
  Plateau:
    mode: 'min'
    patience: 2
    factor: 0.5
    min_lr: 0.000005
  CosineAnnealingLR : 
    T_max : 100
    eta_min : 0.000001
---
audio :
  n_fft : 512
  n_hop : 128
---
data:
  RIR : "/home/data/kbh/DNS-Challenge-16kHz/datasets_fullband/impulse_responses"
  clean : "/home/data/kbh/DNS-Challenge-16kHz/datasets_fullband/clean_fullband/"
  noise : "/home/data/kbh/DNS-Challenge-16kHz/datasets_fullband/noise_fullband"
  
  dev : 
    root : "/home/data/kbh/training_set_sept12_16k/"
  eval :
    clean : "/home/data/kbh/Voicebank+Demand/clean_testset_wav"
    noisy : "/home/data/kbh/Voicebank+Demand/noisy_testset_wav"
  len_data : 49152 # 4096 * 12
  n_item : 65536 # 2^16
  use_RIR : True
  sr : 16000
  SNR : [-15,15]
  target_dB_FS : -25
  target_dB_FS_floating_value :  10
---
log:
  root: '/home/nas/user/kbh/mpSEv2'
  plot_wav : True
  plot_spec : True
  dev : ["PESQ","SNR"]
  eval : ["PESQ","STOI","SNR","DNSMOS", "SigMOS"]
  n_dev : 361