# config for training

trainer:
  checkpoint: "./model_pickle/TRANet_pilot_RIR_TRUloss_for_DNS_app_ver2_2/"
  optimizer: "adamW"
  # 1e-3 => str
  # 1.0e-3 => float
  lr: 1.0e-3
  weight_decay: 1.0e-2
  clip_norm: 5
  min_lr: 1.0e-10
  patience: 3
  factor: 0.6
  disturb_std: 0
  # loss : 'F_SDR' # F_SDR, T_SDR, MSE
  BF_opt: false
  scale_inv: false
  mvn: false
  apply_log: false
  IPD_sincos: false


model_type: "TRANet_v2"


model:
  n_fft : 512
  n_hop : 128
  type_FBlock : "FSA"
  phase_encoder : "PEv5"
  kernel_type : next_v2 #orig, next, GConv
  architecture : {
    "encoder": {
        "enc1": {"in_channels": 64, "out_channels": 64, "kernel_size": [1, 5], "stride": [1,2], "padding": [0,2]},
        # "enc2": {"in_channels": 64, "out_channels": 64, "kernel_size": [1, 3], "stride": [1,1], "padding": [0,1], "groups": 64},
        "enc2": {"in_channels": 64, "out_channels": 64, "kernel_size": [1, 5], "stride": [1,2], "padding": [0,2], "groups": 64},
        # "enc4": {"in_channels": 64, "out_channels": 64, "kernel_size": [1, 3], "stride": [1,1], "padding": [0,1], "groups": 64},
        "enc3": {"in_channels": 64, "out_channels": 64, "kernel_size": [1, 5], "stride": [1,2], "padding": [0,2], "groups": 64},
        ## FSABlock
        "enc4": {"in_channels": 64, "out_channels": 64, "kernel_size": [1, 3], "stride": [1,2], "padding": [0,1], "groups": 32}
    },
    "decoder": {
        ## FSABlock
        "dec4": {"in_channels": 128, "out_channels": 64, "kernel_size": [1, 3], "stride": [1, 2], "padding": [0, 1]},
        "dec3": {"in_channels": 128, "out_channels": 64, "kernel_size": [1, 5], "stride": [1, 2], "padding": [0, 2]},
        # "dec4": {"in_channels": 128, "out_channels": 64, "kernel_size": [1, 3], "stride": [1, 1], "padding": [0, 1]},
        "dec2": {"in_channels": 128, "out_channels": 64, "kernel_size": [1, 5], "stride": [1, 2], "padding": [0, 2]},
        # "dec2": {"in_channels": 128, "out_channels": 64, "kernel_size": [1, 3], "stride": [1, 1], "padding": [0, 1]},
        "dec1": {"in_channels": 128, "out_channels": 8, "kernel_size": [1, 5], "stride": [1, 2], "padding": [0, 2]}
    },
    "FGRU": {"in_channels": 64, "hidden_size": 64, "out_channels": 64},
    "FSA": {"in_channels": 64, "hidden_size": 8, "out_channels": 64},
    "TGRU": {"in_channels": 64, "hidden_size": 64, "out_channels": 64, "state_size": 17},
    "MEA": {"in_channels": 8, "mag_f_dim": 3},
    "PE": {"in_channels": 3, "out_channels" : 64, "type_norm" : "BatchNorm2d"},
    "out": {"in_channels": 8}
}



stft:
  window: "hann"
  frame_shift: 128
  frame_length: 512
  transpose: true



data:
  # RIR : "/home/Uihyeop/nas_Uihyeop/NN_SE/TRANet_MLDR/RIR_filter_stereo_direct"
  RIR : "/home/data2/Uihyeop/DNS-Challenge-16kHz/datasets/impulse_responses"
  clean : "/home/data2/Uihyeop/DNS-Challenge-16kHz/datasets/clean"
  noise : "/home/data2/Uihyeop/DNS-Challenge-16kHz/datasets/noise"

  dev : 
    clean : "/home/data2/Uihyeop/WSJ0"
    n_item : 8192 # 2^16

  test:
    root: "/home/nas/user/Uihyeop/DB/DNS_2020/DNS-Challenge/datasets/test_set/synthetic"

  len_data : 49152 # 4096 * 12
  n_item : 65536 # 2^16
  use_RIR : true
  sr : 16000
  SNR : [0,15] 
  SIR : [0,15] 
  SDR : [-5,25]
  target_dB_FS : -25
  target_dB_FS_floating_value :  10


dataloader:
  shuffle: false
  batch_size: 32
  drop_last: false
  num_workers: 32

dataloader_valid:
  shuffle: false
  batch_size: 32
  drop_last: false
  num_workers: 32

dataloader_test:
  shuffle: False
  batch_size: 1
  drop_last: False
  num_workers: 10


check_point_dir: "./model_pickle/Conv_TasNet/epoch.47.pkl"
inference_scp: "./scp_inference/sample_separation_8k.scp"