task : DNS
---
model:
  mag_only : False
  type : TRUMEA
  use_FSABlock : False
  architecture : orig #orig, half
---
train:
  epoch: 100
  batch_size: 48 # 10
  num_workers: 48 # 10
  optimizer: 'adam'
  adam: 0.001
  adabound:
    initial: 0.001
    final: 0.05
  summary_interval: 100
  validation_interval: 100
  checkpoint_interval: 1000
---
loss:
  type: 'wSDRLoss'
  wSDRLoss :
    alpha : 0.99
  mwMSELoss : 
    alpha : 0.9
  wSDRLoss :
    alpha : 0.99

---
scheduler: # Plateau, oneCycle, CosineAnnealingLR, None
  type: 'Plateau'
  oneCycle:
    max_lr: 0.001
  Plateau:
    mode: 'min'
    patience: 2
    factor: 0.5
    min_lr: 0.000005
  CosineAnnealingLR : 
    T_max : 100
    eta_min : 0.000001
---
audio :
  n_fft : 512
  n_hop : 128
---
data:
  RIR : "/home/data/kbh/DNS-Challenge-16kHz/datasets_fullband/impulse_responses"
  clean : "/home/data/kbh/DNS-Challenge-16kHz/datasets_fullband/clean_fullband/"
  noise : "/home/data/kbh/DNS-Challenge-16kHz/datasets_fullband/noise_fullband"
  
  dev : 
    root : "/home/data/kbh/training_set_sept12_16k/"
    # noisy : [
    #            "/home/data/kbh/training_set_sept12_16k/no_reverb/noisy",
    #            "/home/data/kbh/training_set_sept12_16k/with_reverb/noisy"
    #          ]
    # clean : [
    #            "/home/data/kbh/training_set_sept12_16k/no_reverb/clean",
    #            "/home/data/kbh/training_set_sept12_16k/with_reverb/clean"
    #         ]
  len_data : 49152 # 4096 * 12
  n_item : 65536 # 2^16
  use_RIR : True
  sr : 16000
  SNR : [-10,25]
  target_dB_FS : -25
  target_dB_FS_floating_value :  10
---
log:
  root: '/home/nas/user/kbh/mpSE'
  plot_wav : True
  plot_spec : True
  eval : ["PESQ","STOI","SNR"]
  n_eval : 30 # the number of files to evaluate
