task : SPEAR
---
model:
  type : ResUNetOnFreq # ResUNetOnFreq, ResUNetOnFreq2
  mag_only : true
  use_cdr : false
  activation : "Softplus" # Sigmoid, Softplus
  activation_layer : "PReLU"
  Softplus_thr : 20
  norm : "BatchNorm2d"
  normalize : True
  cplx_enc : false
  dropout : 0.0
  bottleneck : "LSTM" #LSTM, FTGRU
  multi_scale : false
  dB : false
---
apply : 
  hfft_max : 257
---
train:
  epoch: 20
  batch_size: 10 # 10
  num_workers: 10 # 10
  optimizer: 'adam'
  adam: 0.001
  adabound:
    initial: 0.001
    final: 0.05
  summary_interval: 100
  validation_interval: 100
  checkpoint_interval: 1000
---
loss:
  type: 'MSELoss'
  wSDRLoss :
    alpha : 0.9
  mwMSELoss : 
    alpha : 0.9

---
scheduler: # Plateau, oneCycle, None
  type: 'Plateau'
  oneCycle:
    max_lr: 0.0001
  Plateau:
    mode: 'min'
    patience: 2
    factor: 0.5
    min_lr: 0.000005
---
audio :
  n_fft : 512
  n_hop : 128
---
data:
  root: "/home/data2/kbh/SPEAR_seg/"
  dataset : [1,2,3,4]
  len_sec : 5
  sr : 16000
  augment :
    clean : False
    noise : False
    RIR : False
    SNR : [-10,15]
    dBFS : [-60, -30]
    root_RIR : "/home/data2/kbh/impulse_responses/"
    root_clean : "/home/data2/kbh/DNS-Challenge/datasets/clean"
    root_noise : "/home/data2/kbh/DNS-Challenge/datasets/noise"
---
  log:
    root: '/home/nas/user/kbh/SPEAR'
    plot_wav : False
    plot_spec : True