task : SPEAR
---
model:
  type : ResUNetOnFreq
  mag_only : true
  len_sec : 5
  activation : "Softplus" # Sigmoid, Softplus
  Softplus_thr : 20

---
train:
  epoch: 20
  batch_size: 10 # 10
  num_workers: 10 # 10
  optimizer: 'adam'
  adam: 0.001
  adabound:
    initial: 0.001
    final: 0.05
  summary_interval: 100
  validation_interval: 100
  checkpoint_interval: 1000
---
loss:
  type: 'MSELoss'
  wSDRLoss :
    alpha : 0.1
  mwMSELoss : 
    alpha : 0.9
---
scheduler: # Plateau, oneCycle, None
  type: 'Plateau'
  oneCycle:
    max_lr: 0.0001
  Plateau:
    mode: 'min'
    patience: 2
    factor: 0.5
    min_lr: 0.000005
---
audio :
  n_fft : 512
---
data:
  root: "/home/data/kbh/SPEAR_seg/"
  sr : 16000
---
  log:
    root: '/home/nas/user/kbh/SPEAR'
    plot_wav : False
    plot_spec : True